package com.cattailsw.nanidroid.install;

/** Stable structural rejection categories for an untrusted NAR inventory. */
public enum NarInstallError {
    INVALID_ENTRY_METADATA,
    RAW_NAME_LENGTH_LIMIT,
    INVALID_PATH,
    DUPLICATE_ENTRY,
    NORMALIZED_COLLISION,
    FILE_DIRECTORY_COLLISION,
    ENTRY_COUNT_LIMIT,
    PATH_DEPTH_LIMIT,
    PATH_LENGTH_LIMIT,
    COMPONENT_LENGTH_LIMIT,
    INSTALL_DESCRIPTOR_LIMIT,
    DECLARED_ENTRY_SIZE_LIMIT,
    DECLARED_TOTAL_SIZE_LIMIT,
    DECLARED_RATIO_LIMIT,
    MISSING_INSTALL_DESCRIPTOR,
    AMBIGUOUS_LAYOUT,
    MIXED_LAYOUT,
    INVALID_LAYOUT
}
