org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
android.experimental.enableScreenshotTest=true
# Compose Preview Screenshot Testing requires this experimental AGP option.
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
android.compose.screenshot.maxHeapSize=4g
