name: nanidroid-legacy

services:
  build:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: docker/legacy/Dockerfile
    volumes:
      - ../..:/workspace:ro
      - ../../artifacts/legacy:/out

  emulator-native:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: docker/legacy/Dockerfile
    entrypoint: ["bash", "/workspace/docker/emulator/build-native.sh"]
    volumes:
      - ../..:/workspace:ro
      - ../../artifacts/emulator:/out
