package com.cattailsw.nanidroid.install

import java.nio.charset.StandardCharsets.UTF_8
import java.security.MessageDigest
import java.text.Normalizer
import java.util.AbstractList
import java.util.Collections
import org.junit.Assert.*
import org.junit.Test

class NarGhostTreePolicyTest {
    @Test fun stateTargetAndStorageIdentityAreFingerprintBound() {
        val absent=success("ghost",bytes(1),NarGhostTreePolicy.State.ABSENT,entries()); val empty=success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries())
        assertNotEquals(hex(absent.fingerprint),hex(empty.fingerprint)); assertNotEquals(hex(absent.fingerprint),hex(success("other",bytes(1),NarGhostTreePolicy.State.ABSENT,entries()).fingerprint)); assertNotEquals(hex(absent.fingerprint),hex(success("ghost",bytes(2),NarGhostTreePolicy.State.ABSENT,entries()).fingerprint))
        assertEquals(NarGhostTreePolicy.State.ABSENT,absent.state); assertEquals(NarGhostTreePolicy.State.PRESENT,empty.state); assertTrue(empty.entries.isEmpty()); assertEquals(1,empty.fingerprintVersion)
    }
    @Test fun manifestIsSortedTypedAndHasGoldenVersionOneDigest() {
        val abc=digest("abc"); val first=success("ghost",bytes(1,2),NarGhostTreePolicy.State.PRESENT,entries(file("shell/a.txt",3,abc),directory("shell"))); val second=success("ghost",bytes(1,2),NarGhostTreePolicy.State.PRESENT,entries(directory("shell"),file("shell/a.txt",3,abc)))
        assertEquals("shell",first.entries[0].path);assertEquals(NarGhostTreePolicy.Type.DIRECTORY,first.entries[0].type);assertEquals("shell/a.txt",first.entries[1].path);assertEquals(NarGhostTreePolicy.Type.FILE,first.entries[1].type);assertEquals(hex(first.fingerprint),hex(second.fingerprint));assertEquals("966ad96c948762e3d02dba2ef721cc9a2083b73e59deed274fae05b1a9c16f55",hex(first.fingerprint))
        val empty=success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries());val dir=success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries(directory("empty")));val file=success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries(file("empty",0,digest(""))));assertNotEquals(hex(empty.fingerprint),hex(dir.fingerprint));assertNotEquals(hex(dir.fingerprint),hex(file.fingerprint))
    }
    @Test fun pathsNormalizeAndRejectAmbiguityAndUnsafeInput() {
        val nfc=Normalizer.normalize("café",Normalizer.Form.NFC);val nfd=Normalizer.normalize(nfc,Normalizer.Form.NFD);assertEquals(nfc,success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries(directory(nfd))).entries[0].path)
        rejects("NORMALIZED_COLLISION",entries(directory("Alpha"),directory("alpha")));rejects("NORMALIZED_COLLISION",entries(directory(nfc),directory(nfd)));rejects("FILE_DIRECTORY_COLLISION",entries(file("a",0,digest("")),file("a/b",0,digest(""))));rejects("NORMALIZED_COLLISION",entries(directory("A"),file("a/b",0,digest(""))));rejects("MISSING_DIRECTORY",entries(file("a/b",0,digest(""))))
        listOf("",".","..","/root","a//b","a/./b","a/../b","a\\b","a:b","a\u0000b","\ud800").forEach{rejects("INVALID_PATH",entries(directory(it)))}
    }
    @Test fun everyStructuralLimitAcceptsExactAndRejectsPlusOne() {
        assertTrue(build(chain(32,1)).isSuccess());assertError("PATH_DEPTH_LIMIT",build(chain(33,1)));assertTrue(build(entries(directory("a".repeat(255)))).isSuccess());assertError("COMPONENT_LENGTH_LIMIT",build(entries(directory("a".repeat(256)))));assertTrue(build(chain(5,204)).isSuccess());val long=chain(5,204);long[4]=directory(long[4].path!!+"x");assertError("PATH_LENGTH_LIMIT",build(long));assertTrue(build(rootFiles(10000,0)).isSuccess());assertError("ENTRY_COUNT_LIMIT",build(rootFiles(10001,0)));assertTrue(build(entries(file("exact",128L*MIB,digest("")))).isSuccess());assertError("FILE_SIZE_LIMIT",build(entries(file("large",128L*MIB+1,digest("")))));assertTrue(build(rootFiles(4,128L*MIB)).isSuccess());val total=rootFiles(4,128L*MIB);total.add(file("extra",1,digest("")));assertError("TOTAL_SIZE_LIMIT",build(total))
    }
    @Test fun arraysEntriesAndCollectionsAreDefensivelyImmutable() {
        val root=bytes(7,8);val content=digest("payload");val input=file("payload",7,content);val inputs=entries(input);val manifest=success("ghost",root,NarGhostTreePolicy.State.PRESENT,inputs);val fingerprint=hex(manifest.fingerprint);root[0]=99;content[0]=99;inputs.clear();val exposedRoot=manifest.storageRootIdentity;val exposedFingerprint=manifest.fingerprint;val exposedContent=manifest.entries[0].contentDigest!!;exposedRoot[0]=88;exposedFingerprint[0]=88;exposedContent[0]=88;assertEquals(fingerprint,hex(manifest.fingerprint));assertEquals(7,manifest.storageRootIdentity[0].toInt());assertEquals(hex(digest("payload")),hex(manifest.entries[0].contentDigest));assertEquals(1,manifest.entries.size);try{(manifest.entries as MutableList).clear();throw AssertionError("entries were mutable")}catch(_:UnsupportedOperationException){assertEquals(1,manifest.entries.size)}
    }
    @Test fun lengthPrefixesDefeatConcatenationAmbiguity() { val first=success("a","bc".toByteArray(UTF_8),NarGhostTreePolicy.State.PRESENT,entries());val second=success("ab","c".toByteArray(UTF_8),NarGhostTreePolicy.State.PRESENT,entries());assertNotEquals(hex(first.fingerprint),hex(second.fingerprint));val f=success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries(file("a",0,digest("")),directory("b")));val d=success("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries(directory("a"),file("b",0,digest(""))));assertNotEquals(hex(f.fingerprint),hex(d.fingerprint)) }
    @Test fun failuresAreTyped() { assertError("TARGET_ID_INVALID",NarGhostTreePolicy.build("../ghost",bytes(1),NarGhostTreePolicy.State.ABSENT,entries()));assertError("STORAGE_ROOT_ID_INVALID",NarGhostTreePolicy.build("ghost",null,NarGhostTreePolicy.State.ABSENT,entries()));assertError("STATE_INVALID",NarGhostTreePolicy.build("ghost",bytes(1),NarGhostTreePolicy.State.ABSENT,entries(directory("unexpected"))));assertError("CONTENT_DIGEST_INVALID",build(entries(file("bad",0,bytes(1)))));assertError("ENTRY_INVALID",NarGhostTreePolicy.build("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,object:AbstractList<NarGhostTreePolicy.InputEntry>(){override fun get(index:Int):NarGhostTreePolicy.InputEntry=throw SecurityException("get");override val size:Int get()=throw SecurityException("size")})) }
    @Test fun hostileListsUseOneBoundedAuthoritativeSnapshot() {
        val unexpected=directory("unexpected");val falseEmpty=object:AbstractList<NarGhostTreePolicy.InputEntry>(){override fun get(index:Int)=throw IndexOutOfBoundsException();override val size:Int get()=0;override fun isEmpty()=true;override fun iterator(): MutableIterator<NarGhostTreePolicy.InputEntry> = Collections.singletonList(unexpected).iterator()};assertError("STATE_INVALID",NarGhostTreePolicy.build("ghost",bytes(1),NarGhostTreePolicy.State.ABSENT,falseEmpty))
        var consumed=0;val empty=digest("");val underreported=object:AbstractList<NarGhostTreePolicy.InputEntry>(){override fun get(index:Int)=throw IndexOutOfBoundsException();override val size:Int get()=1;override fun iterator()=object:MutableIterator<NarGhostTreePolicy.InputEntry>{override fun hasNext()=consumed<20000;override fun next()=file("f%05d".format(consumed++),0,empty);override fun remove()=throw UnsupportedOperationException()}};assertError("ENTRY_COUNT_LIMIT",NarGhostTreePolicy.build("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,underreported));assertEquals(10001,consumed)
        val runtime=object:AbstractList<NarGhostTreePolicy.InputEntry>(){override fun get(index:Int)=throw IndexOutOfBoundsException();override val size:Int get()=0;override fun iterator(): MutableIterator<NarGhostTreePolicy.InputEntry> = throw SecurityException("iterator")};assertError("ENTRY_INVALID",NarGhostTreePolicy.build("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,runtime))
    }
    private fun build(entries:List<NarGhostTreePolicy.InputEntry>)=NarGhostTreePolicy.build("ghost",bytes(1),NarGhostTreePolicy.State.PRESENT,entries)
    private fun success(target:String,root:ByteArray,state:NarGhostTreePolicy.State,entries:List<NarGhostTreePolicy.InputEntry>):NarGhostTreePolicy.Manifest { val result=NarGhostTreePolicy.build(target,root,state,entries);assertTrue(result.detail,result.isSuccess());assertNotNull(result.manifest);return result.manifest!! }
    private fun rejects(expected:String,entries:List<NarGhostTreePolicy.InputEntry>)=assertError(expected,build(entries)); private fun assertError(expected:String,result:NarGhostTreePolicy.Result){assertFalse(result.isSuccess());assertEquals(expected,result.error!!.name);assertNotNull(result.detail)}
    private fun directory(path:String?)=NarGhostTreePolicy.InputEntry.directory(path);private fun file(path:String?,length:Long,digest:ByteArray?)=NarGhostTreePolicy.InputEntry.file(path,length,digest);private fun entries(vararg values:NarGhostTreePolicy.InputEntry)=ArrayList(values.asList());private fun chain(depth:Int,length:Int):ArrayList<NarGhostTreePolicy.InputEntry>{val result=entries();var path="";repeat(depth){i->path+=if(path.isEmpty())(('a'.code+i%26).toChar().toString().repeat(length)) else "/"+('a'.code+i%26).toChar().toString().repeat(length);result.add(directory(path))};return result};private fun rootFiles(count:Int,length:Long)=ArrayList<NarGhostTreePolicy.InputEntry>().also{r->val empty=digest("");repeat(count){r.add(file("f%05d".format(it),length,empty))}};private fun digest(value:String)=MessageDigest.getInstance("SHA-256").digest(value.toByteArray(UTF_8));private fun bytes(vararg values:Int)=ByteArray(values.size){values[it].toByte()};private fun hex(value:ByteArray?)=value!!.joinToString(""){"%02x".format(it.toInt() and 0xff)}
    private companion object { const val MIB=1024L*1024L }
}
