package com.cattailsw.nanidroid.install

import java.io.*
import java.lang.reflect.Constructor
import java.lang.reflect.Modifier
import java.security.MessageDigest
import org.junit.Assert.*
import org.junit.Test

class NarRetainedOverlayPolicyTest {
 @Test fun absentBaselineProducesSortedArchiveRecipeWithImplicitDirs() { val b=absent("ghost"); val r=success(plan("ghost","ghost","0",wrapper(0,"bundle/"),archiveFile(1,"install.txt",4),archiveFile(2,"Shell/Master/a.txt",7)),b); assertSame(b.manifest,r.baselineManifest()); assertArrayEquals(b.manifest.fingerprint,r.baselineFingerprint()); assertEntries(r,"Shell:DIRECTORY:DIRECTORY:-1:-1","Shell/Master:DIRECTORY:DIRECTORY:-1:-1","Shell/Master/a.txt:FILE:ARCHIVE:0:2","install.txt:FILE:ARCHIVE:1:1"); assertEquals(2,r.fileCount());assertEquals(11,r.totalSize()) }
 @Test fun archiveWinsExactPathsWhileUnlistedFilesAndEmptyDirsSurvive() { val b=present("ghost",directory("empty"),directory("shell"),retainedFile("shell/master.txt",3,0),retainedFile("user.txt",5,1)); val r=success(plan("ghost","ghost","0",archiveFile(0,"shell/master.txt",9)),b);assertEntries(r,"empty:DIRECTORY:DIRECTORY:-1:-1","shell:DIRECTORY:DIRECTORY:-1:-1","shell/master.txt:FILE:ARCHIVE:0:0","user.txt:FILE:RETAINED:1:1");assertEquals(14,r.totalSize());assertArrayEquals(digest(1),r.entries()[3].sha256()) }
 @Test fun archiveFileCannotEraseNonemptyRetainedDirectory() { val n=present("ghost",directory("assets"),retainedFile("assets/user.txt",1,0));assertError("INCOMPATIBLE_GHOST_UPDATE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0",archiveFile(0,"assets",2)),n.manifest,n.inventory));val e=present("ghost",directory("assets"));assertEntries(success(plan("ghost","ghost","0",archiveFile(0,"assets",2)),e),"assets:FILE:ARCHIVE:0:0") }
 @Test fun archiveDirectoryMayReplaceRetainedFile() { val b=present("ghost",retainedFile("shell",2,0));assertEntries(success(plan("ghost","ghost","0",archiveDirectory(0,"shell"),archiveFile(1,"shell/a",1)),b),"shell:DIRECTORY:DIRECTORY:-1:-1","shell/a:FILE:ARCHIVE:0:1");assertEntries(success(plan("ghost","ghost","0",archiveFile(0,"shell/a",1)),b),"shell:DIRECTORY:DIRECTORY:-1:-1","shell/a:FILE:ARCHIVE:0:0") }
 @Test fun spellingTakeoverNeverSilentlyRenamesSurvivingUserPaths() { val f=present("ghost",retainedFile("Readme",1,0));assertEntries(success(plan("ghost","ghost","0",archiveFile(0,"README",2)),f),"README:FILE:ARCHIVE:0:0");val e=present("ghost",directory("Foo"));assertEntries(success(plan("ghost","ghost","0",archiveDirectory(0,"foo")),e),"foo:DIRECTORY:DIRECTORY:-1:-1");val s=present("ghost",directory("Foo"),retainedFile("Foo/user",1,0));assertError("INCOMPATIBLE_GHOST_UPDATE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0",archiveFile(0,"foo/new",1)),s.manifest,s.inventory));val r=present("ghost",directory("Foo"),retainedFile("Foo/old",1,0));assertEntries(success(plan("ghost","ghost","0",archiveFile(0,"foo/old",2)),r),"foo:DIRECTORY:DIRECTORY:-1:-1","foo/old:FILE:ARCHIVE:0:0") }
 @Test fun unicodeAndCaseCollisionsUseOneCrossTreeKey() { val nfc="café";val nfd="café";val b=present("ghost",retainedFile(nfd,1,0));assertEntries(success(plan("ghost","ghost","0",archiveFile(0,nfc,2)),b),"$nfc:FILE:ARCHIVE:0:0");val n=present("ghost",directory(nfc),retainedFile("$nfc/user",1,0));assertError("INCOMPATIBLE_GHOST_UPDATE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0",archiveFile(0,"CAFÉ/new",1)),n.manifest,n.inventory));assertError("MALFORMED_PLAN",build(plan("ghost","ghost","0",archiveFile(0,nfd,1)),absent("ghost"))) }
 @Test fun rejectsUnsupportedDescriptorTargetAndMalformedPlan() { val b=absent("ghost");assertError("UNSUPPORTED_TYPE",build(plan("ghost","shell","0"),b));assertError("UNSUPPORTED_REFRESH",build(plan("ghost","ghost","1"),b));assertError("MALFORMED_PLAN",build(descriptorPlan("ghost","shell",null),b));assertError("UNSUPPORTED_REFRESH",build(descriptorPlan("ghost","ghost","plugin0.refresh"),b));assertError("TARGET_MISMATCH",build(plan("other","ghost","0"),b));assertError("MALFORMED_PLAN",build(plan("ghost","ghost","0",archiveFile(1,"a",1)),b));assertError("MALFORMED_PLAN",build(plan("ghost","ghost","0",archiveFile(0,"A",1),archiveFile(1,"a",1)),b));assertError("MALFORMED_BASELINE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0"),b.manifest,null));val first=present("ghost",retainedFile("first",1,0));val second=present("ghost",retainedFile("second",1,0));assertError("MALFORMED_BASELINE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0"),first.manifest,second.inventory));assertError("MALFORMED_BASELINE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0"),b.manifest,first.inventory));val two=present("ghost",retainedFile("a",1,0),retainedFile("b",1,1));val d=arrayListOf(two.inventory[0],present("ghost",retainedFile("b",1,0)).inventory[0]);assertError("MALFORMED_BASELINE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0"),two.manifest,d));assertError("MALFORMED_BASELINE",NarRetainedOverlayPolicy.build(plan("ghost","ghost","0"),first.manifest,listOf(inventoryEntry(null,1,0)))) }
 @Test fun mergedLimitsAreAppliedAfterReplacement() { val b=present("ghost",rootFiles(10000,0));assertEquals(10000,success(plan("ghost","ghost","0"),b).entries().size);assertError("ENTRY_COUNT_LIMIT",build(plan("ghost","ghost","0",archiveFile(0,"extra",0)),b));val x=Array(5001){i->archiveFile(i,"p%05d/file".format(i),0)};assertError("ENTRY_COUNT_LIMIT",build(plan("ghost","ghost","0",*x),absent("ghost")));assertError("FILE_SIZE_LIMIT",build(plan("ghost","ghost","0",archiveFile(0,"large",128*MIB+1)),absent("ghost")));val u=success(plan("ghost","ghost","0",archiveFile(0,"unknown",-1)),absent("ghost"));assertFalse(u.hasKnownTotalSize());assertEquals(-1,u.totalSize());assertEquals(-1,u.entries()[0].size());val full=present("ghost",retainedFile("a",128*MIB,0),retainedFile("b",128*MIB,1),retainedFile("c",128*MIB,2),retainedFile("d",128*MIB,3));assertError("TOTAL_SIZE_LIMIT",build(plan("ghost","ghost","0",archiveFile(0,"extra",1)),full));assertTrue(build(plan("ghost","ghost","0",archiveFile(0,"a",1)),full).isSuccess()) }
 @Test fun outputIsImmutableNonAuthorizingAndDefensive() { val b=present("ghost",retainedFile("user",1,0));val r=success(plan("ghost","ghost","0"),b);val f=r.baselineFingerprint();val d=r.entries()[0].sha256()!!;f[0]=(f[0].toInt()xor 1).toByte();d[0]=(d[0].toInt()xor 1).toByte();assertArrayEquals(b.manifest.fingerprint,r.baselineFingerprint());assertArrayEquals(digest(0),r.entries()[0].sha256());try{(r.entries() as MutableList<NarRetainedOverlayPolicy.Entry>).clear();throw AssertionError("mutable recipe")}catch(_:UnsupportedOperationException){assertEquals(1,r.entries().size)};assertNotNull(NarRetainedOverlayPolicy::class.java.getAnnotation(Metadata::class.java));for(t in policyTypes()){for(m in t.declaredMethods){assertFalse(File::class.java==m.returnType);assertFalse(InputStream::class.java.isAssignableFrom(m.returnType));assertFalse(OutputStream::class.java.isAssignableFrom(m.returnType));val n=m.name.lowercase();for(x in listOf("path","token","handle","open","write","copy","commit","publish","session","claim"))assertFalse(n,n.contains(x));for(p in m.parameterTypes){assertFalse(File::class.java==p);assertFalse(InputStream::class.java.isAssignableFrom(p));assertFalse(OutputStream::class.java.isAssignableFrom(p));assertFalse(p.name.contains("Claim"))}}};assertNotSame(r.baselineFingerprint(),r.baselineFingerprint()) }
 private fun build(p:NarInstallPlan,b:Baseline)=NarRetainedOverlayPolicy.build(p,b.manifest,b.inventory)
 private fun success(p:NarInstallPlan,b:Baseline):NarRetainedOverlayPolicy.Recipe { val r=build(p,b);assertTrue(r.detail(),r.isSuccess());return r.recipe()!! }
 private fun assertError(e:String,r:NarRetainedOverlayPolicy.Result){assertFalse(r.isSuccess());assertEquals(e,r.error()!!.name);assertFalse(r.detail().isEmpty())}
 private fun assertEntries(r:NarRetainedOverlayPolicy.Recipe,vararg e:String){assertEquals(e.toList(),r.entries().map{"${it.logicalName()}:${it.type().name}:${it.source().name}:${it.finalFileOrdinal()}:${it.sourceOrdinal()}"})}
 private fun policyTypes()=listOf(NarRetainedOverlayPolicy::class.java,*NarRetainedOverlayPolicy::class.java.declaredClasses)
 private fun plan(t:String,type:String,refresh:String,vararg e:NarArchiveInventory.Entry):NarInstallPlan {val m=linkedMapOf("type" to type,"name" to "Ghost","directory" to t,"refresh" to refresh);return NarInstallPlan(0,digest(9),NarArchiveInventory(e.toList(),null,0,0),NarInstallDescriptor(type,"Ghost",t,t,null,m),File("ignored-root"),File("ignored-target"))}
 private fun descriptorPlan(type:String,mt:String,key:String?):NarInstallPlan {val m=linkedMapOf("type" to mt,"name" to "Ghost","directory" to "ghost","refresh" to "0");if(key!=null)m[key]="1";return NarInstallPlan(0,digest(9),NarArchiveInventory(emptyList(),null,0,0),NarInstallDescriptor(type,"Ghost","ghost","ghost",null,m),File("ignored"),File("ignored"))}
 private fun wrapper(o:Int,p:String)=archive(o,p,null,true,0);private fun archiveDirectory(o:Int,p:String)=archive(o,"$p/",p,true,0);private fun archiveFile(o:Int,p:String,s:Long)=archive(o,p,p,false,s);private fun archive(o:Int,raw:String,relative:String?,dir:Boolean,s:Long)=NarArchiveInventory.Entry(o,raw,raw,relative,dir,0,if(dir)0 else 8,s,s)
 private fun absent(t:String):Baseline {val r=NarStagedTreeInventory.absent(t,1,2);assertTrue(r.detail(),r.isSuccess());return Baseline(r.manifest()!!,r.entries())}
 private fun present(t:String,vararg e:BaselineEntry)=present(t,e.toList());private fun present(t:String,e:List<BaselineEntry>):Baseline {val p=Array(e.size){e[it].path};val ty=IntArray(e.size){if(e[it].directory)2 else 1};val s=LongArray(e.size){e[it].size};val o=IntArray(e.size){if(e[it].directory)-1 else e[it].ordinal};val d=ByteArray(e.size*32);e.forEachIndexed{i,x->if(!x.directory)digest(x.ordinal).copyInto(d,i*32)};val r=NarStagedTreeInventory.present(t,NarStagedTreeInventory.Description(1,2,p,ty,s,o,d));assertTrue(r.detail(),r.isSuccess());return Baseline(r.manifest()!!,r.entries())}
 private fun directory(p:String)=BaselineEntry(p,true,0,-1);private fun retainedFile(p:String,s:Long,o:Int)=BaselineEntry(p,false,s,o);private fun rootFiles(n:Int,s:Long)=List(n){retainedFile("f%05d".format(it),s,it)}
 private fun digest(v:Int)=try{MessageDigest.getInstance("SHA-256").digest(byteArrayOf(v.toByte()))}catch(e:Exception){throw AssertionError(e)}
 private fun inventoryEntry(n:String?,s:Long,o:Int):NarStagedTreeInventory.Entry {val c:Constructor<NarStagedTreeInventory.Entry> = NarStagedTreeInventory.Entry::class.java.getDeclaredConstructor(String::class.java,NarGhostTreePolicy.Type::class.java,Long::class.javaPrimitiveType,Int::class.javaPrimitiveType,ByteArray::class.java);c.isAccessible=true;return c.newInstance(n,NarGhostTreePolicy.Type.FILE,s,o,digest(o))}
 private data class Baseline(val manifest:NarGhostTreePolicy.Manifest,val inventory:List<NarStagedTreeInventory.Entry>);private data class BaselineEntry(val path:String,val directory:Boolean,val size:Long,val ordinal:Int)
 private companion object {const val MIB=1024L*1024L}
}
