#!/usr/bin/env python3
"""Generate the common-Kotlin NFKD decomposition table from UnicodeData.txt.

Pinned input: Unicode 17.0.0 UnicodeData.txt
Official source: https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
Expected SHA-256: 2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
Local input: tools/llm-ghost-spike/scripts/UnicodeData-17.0.0.txt (gitignored)

From the repository root, download the pinned source to that exact local path,
then run this script with no arguments. Positional overrides remain available.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


VERSION = "17.0.0"
EXPECTED_SHA256 = "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"
DEFAULT_INPUT = Path("tools/llm-ghost-spike/scripts/UnicodeData-17.0.0.txt")
DEFAULT_OUTPUT = Path(
    "tools/llm-ghost-spike/core/src/commonMain/kotlin/com/cattailsw/nanidroid/"
    "llmghost/generation/UnicodeNfkdData.kt"
)


def chunks(values: list[int], size: int = 64) -> list[list[int]]:
    return [values[index:index + size] for index in range(0, len(values), size)]


def utf16_units(code_point: int) -> list[int]:
    if code_point <= 0xFFFF:
        return [code_point]
    value = code_point - 0x10000
    return [0xD800 + (value >> 10), 0xDC00 + (value & 0x3FF)]


def render_scalar_table(name: str, values: list[int]) -> str:
    units = [unit for value in values for unit in utf16_units(value)]
    lines = ["".join(f"\\u{unit:04X}" for unit in chunk) for chunk in chunks(units)]
    body = " +\n".join(f'        "{line}"' for line in lines)
    return f"    private val {name} = decodeScalars(\n{body}\n    )"


def render_bmp_table(name: str, values: list[int]) -> str:
    lines = ["".join(f"\\u{value:04X}" for value in chunk) for chunk in chunks(values)]
    body = " +\n".join(f'        "{line}"' for line in lines)
    return f"    private val {name}_TEXT =\n{body}\n    private val {name} = IntArray({name}_TEXT.length) {{ {name}_TEXT[it].code }}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("unicode_data", nargs="?", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    payload = args.unicode_data.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(f"UnicodeData SHA-256 mismatch: expected {EXPECTED_SHA256}, got {digest}")

    mappings: list[tuple[int, list[int]]] = []
    combining_classes: list[tuple[int, int]] = []
    for line in payload.decode("utf-8").splitlines():
        fields = line.split(";")
        combining_class = int(fields[3])
        if combining_class:
            combining_classes.append((int(fields[0], 16), combining_class))
        decomposition = fields[5].strip()
        if not decomposition:
            continue
        parts = decomposition.split()
        if parts[0].startswith("<"):
            parts = parts[1:]
        mappings.append((int(fields[0], 16), [int(value, 16) for value in parts]))

    keys: list[int] = []
    offsets = [0]
    values: list[int] = []
    for key, mapping in mappings:
        keys.append(key)
        values.extend(mapping)
        offsets.append(len(values))

    output = f'''// Generated by tools/llm-ghost-spike/scripts/generate_unicode_nfkd.py. Do not edit.
// Unicode {VERSION}; UnicodeData.txt SHA-256 {EXPECTED_SHA256}.
package com.cattailsw.nanidroid.llmghost.generation

internal object UnicodeNfkdData {{
    const val UNICODE_VERSION = "{VERSION}"
    const val SOURCE_SHA256 = "{EXPECTED_SHA256}"

    fun combiningClass(codePoint: Int): Int {{
        val index = findKey(codePoint, COMBINING_KEYS)
        return if (index < 0) 0 else COMBINING_VALUES[index]
    }}

    fun appendDecomposed(codePoint: Int, output: MutableList<Int>, maximumSize: Int) {{
        if (codePoint in HANGUL_FIRST..HANGUL_LAST) {{
            appendHangul(codePoint, output, maximumSize)
            return
        }}
        val index = findKey(codePoint, KEYS)
        if (index < 0) {{
            appendChecked(codePoint, output, maximumSize)
            return
        }}
        for (valueIndex in OFFSETS[index] until OFFSETS[index + 1]) {{
            appendDecomposed(VALUES[valueIndex], output, maximumSize)
        }}
    }}

    private fun appendHangul(codePoint: Int, output: MutableList<Int>, maximumSize: Int) {{
        val syllableIndex = codePoint - HANGUL_FIRST
        appendChecked(L_BASE + syllableIndex / N_COUNT, output, maximumSize)
        appendChecked(V_BASE + (syllableIndex % N_COUNT) / T_COUNT, output, maximumSize)
        val trailingIndex = syllableIndex % T_COUNT
        if (trailingIndex != 0) appendChecked(T_BASE + trailingIndex, output, maximumSize)
    }}

    private fun appendChecked(codePoint: Int, output: MutableList<Int>, maximumSize: Int) {{
        if (output.size >= maximumSize) throw UnicodeExpansionLimitException(maximumSize)
        output += codePoint
    }}

    private fun findKey(codePoint: Int, keys: IntArray): Int {{
        var low = 0
        var high = keys.lastIndex
        while (low <= high) {{
            val middle = (low + high).ushr(1)
            val comparison = keys[middle].compareTo(codePoint)
            when {{
                comparison < 0 -> low = middle + 1
                comparison > 0 -> high = middle - 1
                else -> return middle
            }}
        }}
        return -1
    }}

    private fun decodeScalars(text: String): IntArray {{
        val output = IntArray(text.length)
        var inputIndex = 0
        var outputIndex = 0
        while (inputIndex < text.length) {{
            val first = text[inputIndex++]
            output[outputIndex++] = if (first in '\\uD800'..'\\uDBFF') {{
                val second = text[inputIndex++]
                0x10000 + ((first.code - 0xD800) shl 10) + second.code - 0xDC00
            }} else {{
                first.code
            }}
        }}
        return output.copyOf(outputIndex)
    }}

    private const val HANGUL_FIRST = 0xAC00
    private const val HANGUL_LAST = 0xD7A3
    private const val L_BASE = 0x1100
    private const val V_BASE = 0x1161
    private const val T_BASE = 0x11A7
    private const val T_COUNT = 28
    private const val N_COUNT = 21 * T_COUNT

{render_scalar_table("KEYS", keys)}
{render_bmp_table("OFFSETS", offsets)}
{render_scalar_table("VALUES", values)}
{render_scalar_table("COMBINING_KEYS", [key for key, _ in combining_classes])}
{render_bmp_table("COMBINING_VALUES", [value for _, value in combining_classes])}
}}

internal class UnicodeExpansionLimitException(maximumSize: Int) :
    Exception("NFKD expansion exceeds $maximumSize Unicode scalars.")
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(
        f"Generated {len(keys)} mappings, {len(values)} decomposition scalars, "
        f"and {len(combining_classes)} combining classes for Unicode {VERSION}."
    )


if __name__ == "__main__":
    main()
